# ----------------
# door_config.yaml
# ----------------
door:
  ejepuerta:
    x: 0.8
    y: 0.8
    z: 0.5
    orientacion: 0 # radianes
  apertura:
    picaporte:
      giro: -0.5236 # radianes
      numero_puntos: 10
    puerta:
      giro: -0.5236 # radianes
      numero_puntos: 10
rviz:
  #referenceFrame: /j2s7s300_link_base ## Para simulaciones con j2s7s300
  referenceFrame: /rb1_base_footprint ## Para RB-1