move_group_config:
  #planning_group: "arm"          # Fake node j2s7s300
  planning_group: "j2s7s200_arm"  # Brazo Kinova j2s7s200 RB1
  planning_time: 10
config_arm:
  home:
    x: 0.5
    y: 0
    z: 0.7
    roll: 0
    pitch: 90
    yaw: 0
    joint_1: 170
    joint_2: 310
    joint_3: -20
    joint_4: 330
    joint_5: 0
    joint_6: 280
    joint_7: 100
secure_position_arm: false